default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: spree_db

test:
  <<: *default
  database: spree_test

production:
  <<: *default
  database: spree_db
  username: root
  password: 
